// change this after running find-js-files.js
let automatedBlockUrls = [
  [
    "logbook.itstep.org/assets/8715a633/swagger-ui/dist/swagger-ui.js",
    "script",
    "/js/swagger-ui.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/bootstrap/dist/js/bootstrap.js",
    "script",
    "/js/bootstrap.js",
  ],
  ["logbook.itstep.org/js/library/d3.js", "script", "/js/d3.js"],
  [
    "logbook.itstep.org/assets/8715a633/angular/angular.min.js",
    "script",
    "/js/angular.min.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/angular-ui-router/release/angular-ui-router.min.js",
    "script",
    "/js/angular-ui-router.min.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/angular-animate/angular-animate.min.js",
    "script",
    "/js/angular-animate.min.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/angular-aria/angular-aria.min.js",
    "script",
    "/js/angular-aria.min.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/angular-material/angular-material.min.js",
    "script",
    "/js/angular-material.min.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/angular-messages/angular-messages.min.js",
    "script",
    "/js/angular-messages.min.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/angular-local-storage/dist/angular-local-storage.min.js",
    "script",
    "/js/angular-local-storage.min.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/angular-translate/angular-translate.min.js",
    "script",
    "/js/angular-translate.min.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/angular-toArrayFilter/toArrayFilter.js",
    "script",
    "/js/toArrayFilter.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/angular-translate-loader-url/angular-translate-loader-url.min.js",
    "script",
    "/js/angular-translate-loader-url.min.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/raven-js/dist/raven.js",
    "script",
    "/js/raven.js",
  ],
  [
    "logbook.itstep.org/assets/8715a633/raven-js/dist/plugins/angular.js",
    "script",
    "/js/angular.js",
  ],
  ["logbook.itstep.org/assets/67f4e165/chosen.js", "script", "/js/chosen.js"],
  [
    "logbook.itstep.org/assets/67f4e165/angular-chosen.min.js",
    "script",
    "/js/angular-chosen.min.js",
  ],
  ["logbook.itstep.org/js/angular/script.js", "script", "/js/script.js"],
  [
    "logbook.itstep.org/js/angular/create-graph.js",
    "script",
    "/js/create-graph.js",
  ],
  [
    "logbook.itstep.org/js/angular/directives.js",
    "script",
    "/js/directives.js",
  ],
  [
    "logbook.itstep.org/js/angular/base-factory.js",
    "script",
    "/js/base-factory.js",
  ],
  [
    "logbook.itstep.org/js/angular/base-controller.js",
    "script",
    "/js/base-controller.js",
  ],
  [
    "logbook.itstep.org/js/angular/signal/controllers/signalCtrl.js",
    "script",
    "/js/signalCtrl.js",
  ],
  [
    "logbook.itstep.org/js/angular/signal/signal-factory.js",
    "script",
    "/js/signal-factory.js",
  ],
  [
    "logbook.itstep.org/js/angular/signal/signal-filters.js",
    "script",
    "/js/signal-filters.js",
  ],
  [
    "logbook.itstep.org/assets/273dc59d/controllers/classWorkCtrl.js",
    "script",
    "/js/classWorkCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/273dc59d/classwork-factory.js",
    "script",
    "/js/classwork-factory.js",
  ],
  [
    "logbook.itstep.org/assets/6f179457/controllers/examsCtrl.js",
    "script",
    "/js/examsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/6f179457/exams-factory.js",
    "script",
    "/js/exams-factory.js",
  ],
  [
    "logbook.itstep.org/assets/6f179457/controllers/courseWorksCtrl.js",
    "script",
    "/js/courseWorksCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/85a2823e/controllers/homeWorkCtrl.js",
    "script",
    "/js/homeWorkCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/85a2823e/homeworks-factory.js",
    "script",
    "/js/homeworks-factory.js",
  ],
  [
    "logbook.itstep.org/assets/85a2823e/homeworks-filters.js",
    "script",
    "/js/homeworks-filters.js",
  ],
  [
    "logbook.itstep.org/assets/a4362304/controllers/individualCtrl.js",
    "script",
    "/js/individualCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/a4362304/individual-factory.js",
    "script",
    "/js/individual-factory.js",
  ],
  [
    "logbook.itstep.org/assets/1ea6c6c8/controllers/newsCtrl.js",
    "script",
    "/js/newsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/1ea6c6c8/news-factory.js",
    "script",
    "/js/news-factory.js",
  ],
  [
    "logbook.itstep.org/assets/6fc4f27f/controllers/profileCtrl.js",
    "script",
    "/js/profileCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/6fc4f27f/profile-factory.js",
    "script",
    "/js/profile-factory.js",
  ],
  [
    "logbook.itstep.org/assets/45c15dde/report.helper.js",
    "script",
    "/js/report.helper.js",
  ],
  [
    "logbook.itstep.org/assets/45c15dde/controllers/reportCtrl.js",
    "script",
    "/js/reportCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/45c15dde/report-factory.js",
    "script",
    "/js/report-factory.js",
  ],
  [
    "logbook.itstep.org/assets/43ebfc3e/schedule.helper.js",
    "script",
    "/js/schedule.helper.js",
  ],
  [
    "logbook.itstep.org/assets/43ebfc3e/controllers/scheduleCtrl.js",
    "script",
    "/js/scheduleCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/43ebfc3e/schedule_factory.js",
    "script",
    "/js/schedule_factory.js",
  ],
  [
    "logbook.itstep.org/assets/2239d1d4/controllers/mainStudCtrl.js",
    "script",
    "/js/mainStudCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/2239d1d4/controllers/sendStudentsMailCtrl.js",
    "script",
    "/js/sendStudentsMailCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/2239d1d4/controllers/studentsCommentCtrl.js",
    "script",
    "/js/studentsCommentCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/2239d1d4/controllers/studentsCtrl.js",
    "script",
    "/js/studentsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/2239d1d4/controllers/studentProfileCtrl.js",
    "script",
    "/js/studentProfileCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/2239d1d4/students-module.js",
    "script",
    "/js/students-module.js",
  ],
  [
    "logbook.itstep.org/assets/2239d1d4/students-factory.js",
    "script",
    "/js/students-factory.js",
  ],
  [
    "logbook.itstep.org/assets/7a7b27f4/controllers/tasksCtrl.js",
    "script",
    "/js/tasksCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/7a7b27f4/tasks-factory.js",
    "script",
    "/js/tasks-factory.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/bind_factory.js",
    "script",
    "/js/bind_factory.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/bindFormsCtrl.js",
    "script",
    "/js/bindFormsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/bindMainCtrl.js",
    "script",
    "/js/bindMainCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/bindMaterialsCtrl.js",
    "script",
    "/js/bindMaterialsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/bindTeachMaterialsCtrl.js",
    "script",
    "/js/bindTeachMaterialsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/bindCityCtrl.js",
    "script",
    "/js/bindCityCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/linkingMainCtrl.js",
    "script",
    "/js/linkingMainCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/linkingMethodCtrl.js",
    "script",
    "/js/linkingMethodCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/linkingSpecCtrl.js",
    "script",
    "/js/linkingSpecCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/bindAuthorsCtrl.js",
    "script",
    "/js/bindAuthorsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/linkingFormCtrl.js",
    "script",
    "/js/linkingFormCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/logsCtrl.js",
    "script",
    "/js/logsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/linkingDirectionCtrl.js",
    "script",
    "/js/linkingDirectionCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/linkingEditSpecCtrl.js",
    "script",
    "/js/linkingEditSpecCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/logs/materialsLogsCtrl.js",
    "script",
    "/js/materialsLogsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/logs/methodPackageLogsCtrl.js",
    "script",
    "/js/methodPackageLogsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/logs/mainLogsCtrl.js",
    "script",
    "/js/mainLogsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/logs/methodLinkingLogsCtrl.js",
    "script",
    "/js/methodLinkingLogsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/logs/methodBindLogsCtrl.js",
    "script",
    "/js/methodBindLogsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/controllers/logs/methodPublicSpecLogsCtrl.js",
    "script",
    "/js/methodPublicSpecLogsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/bef04cf/logs_factory.js",
    "script",
    "/js/logs_factory.js",
  ],
  [
    "logbook.itstep.org/assets/4185b7e4/controllers/groupsCtrl.js",
    "script",
    "/js/groupsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/4185b7e4/groups-factory.js",
    "script",
    "/js/groups-factory.js",
  ],
  [
    "logbook.itstep.org/assets/ef63eace/controllers/portfolioCtrl.js",
    "script",
    "/js/portfolioCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/ef63eace/portfolio-factory.js",
    "script",
    "/js/portfolio-factory.js",
  ],
  [
    "logbook.itstep.org/assets/b8174e82/presents_factory.js",
    "script",
    "/js/presents_factory.js",
  ],
  [
    "logbook.itstep.org/assets/b8174e82/controllers/presentsCtrl.js",
    "script",
    "/js/presentsCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/b8174e82/controllers/addMaterialCtrl.js",
    "script",
    "/js/addMaterialCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/b8174e82/controllers/addHomeWorkCtrl.js",
    "script",
    "/js/addHomeWorkCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/b8174e82/controllers/addLabWorkCtrl.js",
    "script",
    "/js/addLabWorkCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/e2911627/home/controllers/homeCtrl.js",
    "script",
    "/js/homeCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/e2911627/home/home-factory.js",
    "script",
    "/js/home-factory.js",
  ],
  [
    "logbook.itstep.org/assets/e2911627/dateService.js",
    "script",
    "/js/dateService.js",
  ],
  [
    "logbook.itstep.org/assets/faae6642/controllers/certificatesCtrl.js",
    "script",
    "/js/certificatesCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/faae6642/certificates_factory.js",
    "script",
    "/js/certificates_factory.js",
  ],
  [
    "logbook.itstep.org/assets/20bfc67c/controllers/dossierCtrl.js",
    "script",
    "/js/dossierCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/20bfc67c/dossier-factory.js",
    "script",
    "/js/dossier-factory.js",
  ],
  [
    "logbook.itstep.org/assets/f2fa08ff/controllers/TraficCtrl.js",
    "script",
    "/js/TraficCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/f2fa08ff/traffic-factory.js",
    "script",
    "/js/traffic-factory.js",
  ],
  [
    "logbook.itstep.org/assets/f4ad3e4f/controllers/contentAuthorCtrl.js",
    "script",
    "/js/contentAuthorCtrl.js",
  ],
  [
    "logbook.itstep.org/assets/f4ad3e4f/content-factory.js",
    "script",
    "/js/content-factory.js",
  ],
];

export { automatedBlockUrls };
